import sys
t5 = '\t' * 5
t6 = '\t' * 6
t7 = '\t' * 7
with open('src/index.ts', 'r') as f:
    content = f.read()

# Build the insertion block
lines = []
lines.append(t5 + '// --- Flow output tracking for TUI overlay ---')
lines.append(t5 + 'const flowOutputs = new Map<string, FlowOutputEntry>();')
lines.append(t5 + 'let removeListener: (() => void) | undefined;')
lines.append(t5 + 'let overlayHandle: any;')
lines.append(t5 + 'let focusedView: any;')
lines.append('')
lines.append(t5 + '// Wrap onUpdate to populate flowOutputs for the overlay')
lines.append(t5 + 'const wrappedOnUpdate = (partial: any) => {')
lines.append(t6 + 'const results = partial.details?.results as Array<{')
lines.append(t7 + 'type: string;')
lines.append(t7 + 'aim: string;')
lines.append(t7 + 'thinkingText?: string;')
lines.append(t7 + 'streamingText?: string;')
lines.append(t7 + 'errorMessage?: string;')
lines.append(t7 + 'exitCode?: number;')
lines.append(t6 + '}> | undefined;')
lines.append(t6 + 'if (results) {')
lines.append(t6 + '    results.forEach((r, i) => {')
lines.append(t6 + '        const key = `${r.type}#${i}`;')
lines.append(t6 + '        const existing = flowOutputs.get(key);')
lines.append(t6 + '        flowOutputs.set(key, {')
lines.append(t6 + '            type: r.type,')
lines.append(t6 + '            aim: r.aim || \'\',')
lines.append(t6 + '            running: r.exitCode === undefined || r.exitCode === -1,')
lines.append(t6 + '            transcript: existing?.transcript || [],')
lines.append(t6 + '            streamingThinking: r.thinkingText || \'\',')
lines.append(t6 + '            streamingOutput: r.streamingText || \'\',')
lines.append(t6 + '            errorMessage: r.errorMessage || existing?.errorMessage,')
lines.append(t6 + '        });')
lines.append(t6 + '    });')
lines.append(t6 + '}')
lines.append(t6 + 'onUpdate?.(partial);')
lines.append(t5 + '};')
lines.append('')
lines.append(t5 + '// Register Ctrl+O hotkey for flow overlay')
lines.append(t5 + 'if (ctx.hasUI && ctx.ui && typeof ctx.ui.onTerminalInput === \'function\') {')
lines.append(t6 + 'removeListener = ctx.ui.onTerminalInput((data: string) => {')
lines.append(t6 + '    if (!matchesKey(data, Key.ctrl(\'o\'))) return undefined;')
lines.append(t6 + '    if (overlayHandle && !overlayHandle.isHidden?.()) {')
lines.append(t6 + '        overlayHandle.setHidden?.(true);')
lines.append(t6 + '    }')
lines.append(t6 + '    const pickerFlows = Array.from(flowOutputs.entries()).map(([key, entry]) => ({')
lines.append(t6 + '        key, type: entry.type, aim: entry.aim, running: entry.running,')
lines.append(t6 + '    }));')
lines.append(t6 + '    if (pickerFlows.length === 0) return { consume: true };')
lines.append(t6 + '    ctx.ui.custom<string | null>(')
lines.append(t6 + '        (tui: any, theme: any, kb: any, done: (result: string | null) => void) => {')
lines.append(t6 + '            return new FlowPicker(pickerFlows, tui, theme, kb, done);')
lines.append(t6 + '        },')
lines.append(t6 + "        { overlay: true, overlayOptions: { anchor: 'center' as const, width: 60, minWidth: 40, maxHeight: '60%', margin: 1 } },")
lines.append(t6 + '    ).then((selectedKey: string | null) => {')
lines.append(t6 + '        if (!selectedKey) return;')
lines.append(t6 + '        const entry = flowOutputs.get(selectedKey);')
lines.append(t6 + '        if (!entry) return;')
lines.append(t6 + '        focusedView = new FlowFocusedView(')
lines.append(t6 + '            selectedKey, entry, ctx.ui, ctx.ui.theme || {}, ctx.ui.keybindings || {},')
lines.append(t6 + '            () => { if (overlayHandle) overlayHandle.setHidden?.(true); },')
lines.append(t6 + '            () => {')
lines.append(t6 + '                if (overlayHandle) overlayHandle.setHidden?.(true);')
lines.append(t6 + '                const pf = Array.from(flowOutputs.entries()).map(([k, e]) => ({ key: k, type: e.type, aim: e.aim, running: e.running }));')
lines.append(t6 + '                ctx.ui.custom<string | null>(')
lines.append(t6 + '                    (tui: any, theme: any, kb: any, done: (r: string | null) => void) => new FlowPicker(pf, tui, theme, kb, done),')
lines.append(t6 + "                    { overlay: true, overlayOptions: { anchor: 'center' as const, width: 60, minWidth: 40, maxHeight: '60%', margin: 1 } },")
lines.append(t6 + '                ).then((sk: string | null) => {')
lines.append(t6 + '                    if (!sk) return;')
lines.append(t6 + '                    const e2 = flowOutputs.get(sk);')
lines.append(t6 + '                    if (!e2) return;')
lines.append(t6 + '                    focusedView = new FlowFocusedView(sk, e2, ctx.ui, ctx.ui.theme || {}, ctx.ui.keybindings || {},')
lines.append(t6 + '                        () => { if (overlayHandle) overlayHandle.setHidden?.(true); });')
lines.append(t6 + '                    ctx.ui.custom(')
lines.append(t6 + '                        (tui: any, theme: any, kb: any, done: (r: any) => void) => focusedView,')
lines.append(t6 + "                        { overlay: true, overlayOptions: { anchor: 'center' as const, width: 70, minWidth: 50, maxHeight: '80%', margin: 1, onHandle: (h: any) => { overlayHandle = h; } } },")
lines.append(t6 + '                    );')
lines.append(t6 + '                });')
lines.append(t6 + '            },')
lines.append(t6 + '        );')
lines.append(t6 + '        ctx.ui.custom(')
lines.append(t6 + '            (tui: any, theme: any, kb: any, done: (r: any) => void) => focusedView,')
lines.append(t6 + '            {')
lines.append(t6 + '                overlay: true,')
lines.append(t6 + '                overlayOptions: {')
lines.append(t6 + "                    anchor: 'center' as const,")
lines.append(t6 + '                    width: 70,')
lines.append(t6 + '                    minWidth: 50,')
lines.append(t6 + "                    maxHeight: '80%',")
lines.append(t6 + '                    margin: 1,')
lines.append(t6 + '                    onHandle: (h: any) => { overlayHandle = h; },')
lines.append(t6 + '                },')
lines.append(t6 + '            },')
lines.append(t6 + '        );')
lines.append(t6 + '    });')
lines.append(t6 + '    return { consume: true };')
lines.append(t6 + '});')
lines.append(t5 + '}')
lines.append('')

insertion = '\n'.join(lines)

# EDIT 1: Insert before executeFlows
old1 = t5 + 'const result = await executeFlows('
content = content.replace(old1, insertion + old1, 1)

# EDIT 2: onUpdate -> wrappedOnUpdate
content = content.replace(t6 + 'onUpdate,', t6 + 'onUpdate: wrappedOnUpdate,', 1)

# EDIT 3: cleanup after executeFlows
old3 = t5 + ');\n\n' + t5 + 'const flowToolResult = {'
new3 = t5 + ');\n\n' + t5 + '// Cleanup: remove hotkey listener after flows complete\n' + t5 + 'removeListener?.();\n\n' + t5 + 'const flowToolResult = {'
content = content.replace(old3, new3, 1)

with open('src/index.ts', 'w') as f:
    f.write(content)
print(f"Done. Lines: {len(content.splitlines())}")
